# Generated by Django 2.1 on 2023-07-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitUserRegisterModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('pswd', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('pan', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(default='waiting', max_length=100)),
                ('authkey', models.CharField(default='waiting', max_length=100)),
                ('cdate', models.DateTimeField()),
            ],
            options={
                'db_table': 'userregister',
            },
        ),
        migrations.CreateModel(
            name='BlockChainLedger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customeremail', models.CharField(max_length=100)),
                ('agentemail', models.CharField(max_length=100)),
                ('currencyname', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('paidammout', models.FloatField()),
                ('blockchainmoney', models.FloatField()),
            ],
            options={
                'db_table': 'BlockChainLedger',
            },
        ),
        migrations.CreateModel(
            name='CustomerHadCoins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currencyName', models.CharField(max_length=100)),
                ('customeremail', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'CustomerContainCoins',
            },
        ),
        migrations.CreateModel(
            name='UserBuyingCryptoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customername', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('currencyname', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('agentemail', models.CharField(max_length=100)),
                ('singlecoingamount', models.FloatField()),
                ('payableammount', models.FloatField()),
                ('cardnumber', models.CharField(max_length=100)),
                ('nameoncard', models.CharField(max_length=100)),
                ('cardexpiry', models.CharField(max_length=100)),
                ('cvv', models.IntegerField()),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'UserBuyingCryptoModel',
            },
        ),
        migrations.AlterUniqueTogether(
            name='customerhadcoins',
            unique_together={('currencyName', 'customeremail')},
        ),
    ]
